"""Change publication date for year in Book

Revision ID: ab920513c80d
Revises: ad227cc0ed43
Create Date: 2024-09-05 00:07:40.155051

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab920513c80d'
down_revision: Union[str, None] = 'ad227cc0ed43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('publication_year', sa.Integer(), nullable=True))
    op.drop_column('book', 'publication_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('publication_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('book', 'publication_year')
    # ### end Alembic commands ###
