"""Birthdate optional in Author and prof picture add to User

Revision ID: d1d4c44a818c
Revises: 4bd3df607def
Create Date: 2024-10-07 00:04:09.414281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d4c44a818c'
down_revision: Union[str, None] = '4bd3df607def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'country',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.add_column('user', sa.Column('profile_picture', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_picture')
    op.alter_column('author', 'country',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    # ### end Alembic commands ###
