"""Add User model

Revision ID: 2857da934edd
Revises: 
Create Date: 2024-07-17 19:28:55.461197

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2857da934edd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('name', sa.String(length=60), nullable=False),
        sa.Column('first_last_name', sa.String(length=60), nullable=False),
        sa.Column('second_last_name', sa.String(length=60), nullable=True),
        sa.Column('date_of_birth', sa.DateTime(), nullable=True),
        sa.Column('user_role', sa.Enum('ADMIN', 'USER', 'AUTHOR', name='userrole'), nullable=False),
        sa.Column('phone_number', sa.String(length=12), nullable=True),
        sa.Column('phone_country_code', sa.String(length=4), nullable=True),
        sa.Column('username', sa.String(length=15), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(length=60), nullable=False),
        sa.Column('password', sa.String(length=120), nullable=False),
        sa.Column('login_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
        sa.Column('logged_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('disabled', sa.Boolean(), server_default=sa.text('false'), nullable=True),
        sa.Column('disabled_at', sa.DateTime(), nullable=True),
        sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('disabled_by', sa.Integer(), nullable=True),
        sa.Column('modified_by', sa.Integer(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='fk_created_by'),
        sa.ForeignKeyConstraint(['disabled_by'], ['user.id'], name='fk_disabled_by'),
        sa.ForeignKeyConstraint(['modified_by'], ['user.id'], name='fk_modified_by'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
