"""Add access_token model

Revision ID: 4bd3df607def
Revises: ab920513c80d
Create Date: 2024-09-22 19:10:42.179415

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd3df607def'
down_revision: Union[str, None] = 'ab920513c80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'access_token',
        sa.Column('access_token', sa.String(), nullable=False),
        sa.Column('valid', sa.Boolean(), nullable=False),
        sa.Column('expiration', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('access_token'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_token')
    # ### end Alembic commands ###
