"""Add status to Book model

Revision ID: 03745fad6afc
Revises: 85efb39b3d46
Create Date: 2024-08-20 19:38:46.113343

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03745fad6afc'
down_revision: Union[str, None] = '85efb39b3d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bookstatus = postgresql.ENUM('ACTIVE', 'PENDING', 'REJECTED', 'DELETED', name='bookstatus', create_type=False)
    bookstatus.create(op.get_bind(), checkfirst=True)
    op.add_column('book', sa.Column('status', bookstatus, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'status')
    # ### end Alembic commands ###
