"""Add Review model

Revision ID: 85efb39b3d46
Revises: 71cf22336509
Create Date: 2024-07-27 11:12:58.269155

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85efb39b3d46'
down_revision: Union[str, None] = '71cf22336509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'review',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('title', sa.String(length=140), nullable=False),
        sa.Column('content', sa.String(length=2000), nullable=False),
        sa.Column('rating', sa.Integer(), nullable=False),
        sa.Column('book_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('disabled', sa.Boolean(), server_default=sa.text('false'), nullable=True),
        sa.Column('disabled_at', sa.DateTime(), nullable=True),
        sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('disabled_by', sa.Integer(), nullable=True),
        sa.Column('modified_by', sa.Integer(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['book_id'], ['book.id'], name='fk_review_book_id', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='fk_created_by'),
        sa.ForeignKeyConstraint(['disabled_by'], ['user.id'], name='fk_disabled_by'),
        sa.ForeignKeyConstraint(['modified_by'], ['user.id'], name='fk_modified_by'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_review_user_id', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
