"""Add Author User relationship

Revision ID: ad227cc0ed43
Revises: a00aad9b1055
Create Date: 2024-09-01 17:46:08.421972

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad227cc0ed43'
down_revision: Union[str, None] = 'a00aad9b1055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_user_author_id', 'user', 'author', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_author_id', 'user', type_='foreignkey')
    op.drop_column('user', 'author_id')
    # ### end Alembic commands ###
