"""Add Author, Book and Genre models

Revision ID: 71cf22336509
Revises: 2857da934edd
Create Date: 2024-07-24 18:33:42.198592

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71cf22336509'
down_revision: Union[str, None] = '2857da934edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'author',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=60), nullable=False),
        sa.Column('first_last_name', sa.String(length=60), nullable=False),
        sa.Column('second_last_name', sa.String(length=60), nullable=True),
        sa.Column('date_of_birth', sa.DateTime(), nullable=True),
        sa.Column('country', sa.String(length=60), nullable=False),
        sa.Column('city', sa.String(length=60), nullable=True),
        sa.Column('biography', sa.String(length=1200), nullable=True),
        sa.Column('picture', sa.String(length=1000), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('disabled', sa.Boolean(), server_default=sa.text('false'), nullable=True),
        sa.Column('disabled_at', sa.DateTime(), nullable=True),
        sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('disabled_by', sa.Integer(), nullable=True),
        sa.Column('modified_by', sa.Integer(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='fk_created_by'),
        sa.ForeignKeyConstraint(['disabled_by'], ['user.id'], name='fk_disabled_by'),
        sa.ForeignKeyConstraint(['modified_by'], ['user.id'], name='fk_modified_by'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'book',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('title', sa.String(length=140), nullable=False),
        sa.Column('overview', sa.String(length=1200), nullable=False),
        sa.Column('isbn', sa.String(length=20), nullable=False),
        sa.Column('publisher', sa.String(length=80), nullable=True),
        sa.Column('publication_date', sa.DateTime(), nullable=True),
        sa.Column('pages', sa.Integer(), nullable=True),
        sa.Column('cover', sa.String(length=1000), nullable=True),
        sa.Column('language', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('disabled', sa.Boolean(), server_default=sa.text('false'), nullable=True),
        sa.Column('disabled_at', sa.DateTime(), nullable=True),
        sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('disabled_by', sa.Integer(), nullable=True),
        sa.Column('modified_by', sa.Integer(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='fk_created_by'),
        sa.ForeignKeyConstraint(['disabled_by'], ['user.id'], name='fk_disabled_by'),
        sa.ForeignKeyConstraint(['modified_by'], ['user.id'], name='fk_modified_by'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'genre',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=60), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('disabled', sa.Boolean(), server_default=sa.text('false'), nullable=True),
        sa.Column('disabled_at', sa.DateTime(), nullable=True),
        sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('disabled_by', sa.Integer(), nullable=True),
        sa.Column('modified_by', sa.Integer(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='fk_created_by'),
        sa.ForeignKeyConstraint(['disabled_by'], ['user.id'], name='fk_disabled_by'),
        sa.ForeignKeyConstraint(['modified_by'], ['user.id'], name='fk_modified_by'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'author_book',
        sa.Column('author_id', sa.Integer(), nullable=False),
        sa.Column('book_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['author_id'],
            ['author.id'],
        ),
        sa.ForeignKeyConstraint(
            ['book_id'],
            ['book.id'],
        ),
        sa.PrimaryKeyConstraint('author_id', 'book_id'),
    )
    op.create_table(
        'book_genre',
        sa.Column('book_id', sa.Integer(), nullable=False),
        sa.Column('genre_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['book_id'],
            ['book.id'],
        ),
        sa.ForeignKeyConstraint(
            ['genre_id'],
            ['genre.id'],
        ),
        sa.PrimaryKeyConstraint('book_id', 'genre_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_genre')
    op.drop_table('author_book')
    op.drop_table('genre')
    op.drop_table('book')
    op.drop_table('author')
    # ### end Alembic commands ###
