"""Add Publisher model

Revision ID: a00aad9b1055
Revises: 03745fad6afc
Create Date: 2024-08-31 16:43:38.004806

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a00aad9b1055'
down_revision: Union[str, None] = '03745fad6afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'publisher',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=140), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('disabled', sa.Boolean(), server_default=sa.text('false'), nullable=True),
        sa.Column('disabled_at', sa.DateTime(), nullable=True),
        sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('disabled_by', sa.Integer(), nullable=True),
        sa.Column('modified_by', sa.Integer(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='fk_created_by'),
        sa.ForeignKeyConstraint(['disabled_by'], ['user.id'], name='fk_disabled_by'),
        sa.ForeignKeyConstraint(['modified_by'], ['user.id'], name='fk_modified_by'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.add_column('book', sa.Column('publisher_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_book_publisher_id', 'book', 'publisher', ['publisher_id'], ['id'], ondelete='CASCADE')
    op.drop_column('book', 'publisher')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('publisher', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint('fk_book_publisher_id', 'book', type_='foreignkey')
    op.drop_column('book', 'publisher_id')
    op.drop_table('publisher')
    # ### end Alembic commands ###
