"""Add Book list model

Revision ID: f66b79bfd056
Revises: 4ce58f56b479
Create Date: 2025-06-08 11:01:45.120901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66b79bfd056'
down_revision: Union[str, None] = '4ce58f56b479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('disabled', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('disabled_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='fk_created_by'),
    sa.ForeignKeyConstraint(['disabled_by'], ['user.id'], name='fk_disabled_by'),
    sa.ForeignKeyConstraint(['modified_by'], ['user.id'], name='fk_modified_by'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_book_list_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_list_book',
    sa.Column('book_list_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_list_id'], ['book_list.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_list_id', 'book_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_list_book')
    op.drop_table('book_list')
    # ### end Alembic commands ###
